Return-Path: <aettlinger@worldnet.att.net>
Delivered-To: shlomif@vipe.technion.ac.il
Received: (qmail 21461 invoked from network); 14 Nov 2001 11:31:51 -0000
Received: from mtiwmhc25.worldnet.att.net (204.127.131.50)
  by vipe.technion.ac.il with SMTP; 14 Nov 2001 11:31:51 -0000
Received: from computer ([12.78.218.17]) by mtiwmhc25.worldnet.att.net
          (InterMail vM.4.01.03.27 201-229-121-127-20010626) with SMTP
          id <20011114113143.IUOI11294.mtiwmhc25.worldnet.att.net@computer>
          for <shlomif@vipe.technion.ac.il>;
          Wed, 14 Nov 2001 11:31:43 +0000
Message-ID: <000601c16cff$e2efa120$11da4e0c@computer>
From: "Adrian Ettlinger" <aettlinger@worldnet.att.net>
To: "Shlomi Fish" <shlomif@vipe.technion.ac.il>
References: <Pine.LNX.4.33L2.0111140939270.19020-100000@vipe.technion.ac.il>
Subject: Guessing where you're at
Date: Wed, 14 Nov 2001 06:30:27 -0500
MIME-Version: 1.0
Content-Type: text/plain;
  charset="iso-8859-1"
Content-Transfer-Encoding: 7bit
X-Priority: 3
X-MSMail-Priority: Normal
X-Mailer: Microsoft Outlook Express 5.00.2615.200
X-MimeOLE: Produced By Microsoft MimeOLE V5.00.2615.200
Status: RO
X-Status: A
X-Keywords: 
X-UID: 26
X-KMail-EncryptionState: 
X-KMail-SignatureState: 
X-KMail-MDN-Sent: 

Hi Shlomi,

    Roaming over the globe in my mind, if I had to make a guess -- albeit
not a high-confidence one-- I'd guess that "il" is the Internet code for
Israel.  Other evidence:  Your given name, which I've never heard before,
but has a Jewish ring to it.  The fact that you replied quickly to a message
sent in the middle of the night here, implying you're in a distant time
zone.

    If I guessed right, that would sort of preclude our casually getting
together for lunch.

    Also means I'll have to be careful to avoid diluting our conversation
with a lot of non-freecell talk.  I happen to be of Jewish extraction
myself -- but very secular.

Best regards, ----------------Adrian  (or should I have said "Shalom"?)


