Return-Path: <aettlinger@worldnet.att.net>
Delivered-To: shlomif@vipe.technion.ac.il
Received: (qmail 9726 invoked from network); 17 Nov 2001 04:55:48 -0000
Received: from mtiwmhc22.worldnet.att.net (204.127.131.47)
  by vipe.technion.ac.il with SMTP; 17 Nov 2001 04:55:48 -0000
Received: from computer ([12.78.221.76]) by mtiwmhc22.worldnet.att.net
          (InterMail vM.4.01.03.27 201-229-121-127-20010626) with SMTP
          id <20011117045540.NBPP4554.mtiwmhc22.worldnet.att.net@computer>
          for <shlomif@vipe.technion.ac.il>;
          Sat, 17 Nov 2001 04:55:40 +0000
Message-ID: <002f01c16f24$0cc61b20$4cdd4e0c@computer>
From: "Adrian Ettlinger" <aettlinger@worldnet.att.net>
To: "Shlomi Fish" <shlomif@vipe.technion.ac.il>
References: <Pine.LNX.4.33L2.0111170409270.2432-100000@vipe.technion.ac.il>
Subject: Re: Freecell solvers, +
Date: Fri, 16 Nov 2001 23:16:18 -0500
MIME-Version: 1.0
Content-Type: text/plain;
  charset="iso-8859-1"
Content-Transfer-Encoding: 7bit
X-Priority: 3
X-MSMail-Priority: Normal
X-Mailer: Microsoft Outlook Express 5.00.2615.200
X-MIMEOLE: Produced By Microsoft MimeOLE V5.00.2615.200
Status: RO
X-Status: A
X-Keywords: 
X-UID: 31
X-KMail-EncryptionState: 
X-KMail-SignatureState: 
X-KMail-MDN-Sent: 

Hi Shlomi,

<<I think my grandmother or her parents lived through the times of the
Ottoman Empire, so their ancestors were in Iraq at least that old.>>
    It always interests me to hear of Jewish populations which have stuck it
out in various places in the Middle East.  I was fascinated when I first
heard that there are Jewish populations in Israel who have been there
continuously since Roman Empire times.

<<I run it over ranges of 1000 or so games. It's quite fast, but I'm not
sure that as fast as Don Woods'.>>
    I don't consider Don Woods' original program that fast.  When it goes up
to 100,000 iterations or so, it really slows down to a snail's pace.  I
didn't try to figure it out from your code, but what does the multiple test
program do by way of reporting its results when it plows through multiple
boards?

<<Have you been using some of the standard ANSI C library, or do you stick
to the Win32 API ones?>>
    Hmmm, darned if I know.  I just use the commands that I find in the Help
system that comes with the VC++ version I'm using.  I assume some of those
are from the standard ANSI C library.  But I must confess that I've never
had a reason to be sensitive to whether a command was standard or not.  I
suppose that's because I work only for myself and don't need to have any
concern for portability to others.

    I took my first fresh look at the FcPro code a little while ago, and at
first glance, this is going to take some head-scratching.  Like your
quotation that it's easier to write code than to read it.  Even reading my
own code that I haven't looked at for over a year or two.  Hope it doesn't
turn out to be to big a can of worms.

Best regards,  --------------Adrian


