Return-Path: <aettlinger@worldnet.att.net>
Delivered-To: shlomif@vipe.technion.ac.il
Received: (qmail 20625 invoked from network); 14 Nov 2001 10:02:16 -0000
Received: from mtiwmhc22.worldnet.att.net (204.127.131.47)
  by vipe.technion.ac.il with SMTP; 14 Nov 2001 10:02:16 -0000
Received: from computer ([12.78.220.34]) by mtiwmhc22.worldnet.att.net
          (InterMail vM.4.01.03.27 201-229-121-127-20010626) with SMTP
          id <20011114100212.OCJH4554.mtiwmhc22.worldnet.att.net@computer>
          for <shlomif@vipe.technion.ac.il>;
          Wed, 14 Nov 2001 10:02:12 +0000
Message-ID: <002d01c16cf3$6168dec0$3af94e0c@computer>
From: "Adrian Ettlinger" <aettlinger@worldnet.att.net>
To: "Shlomi Fish" <shlomif@vipe.technion.ac.il>
References: <Pine.LNX.4.33L2.0111140939270.19020-100000@vipe.technion.ac.il>
Subject: Integrating FCS with Freecell Pro
Date: Wed, 14 Nov 2001 05:00:46 -0500
MIME-Version: 1.0
Content-Type: text/plain;
  charset="iso-8859-1"
Content-Transfer-Encoding: 7bit
X-Priority: 3
X-MSMail-Priority: Normal
X-Mailer: Microsoft Outlook Express 5.00.2615.200
X-MimeOLE: Produced By Microsoft MimeOLE V5.00.2615.200
Status: RO
X-Status: A
X-Keywords: 
X-UID: 24
X-KMail-EncryptionState: 
X-KMail-SignatureState: 
X-KMail-MDN-Sent: 

Hi Shlomi,

    Aha! So you're the author.  Great.

    We should be able to work together very well.  I don't mind at all
sharing the FcPro code with you.  But I must tell you at the outset that I
am not really a professional programmer.  I've written a lot of code, and
done some, at the risk of sounding immodest, neat applications.  But my
background is that of an EE who got into software engineering "late in
life", so I wasn't raised on the kind of discipline these young Computer
Science grads have.  So the code, by any real standards, is very poorly
documented.

    I'll also tell you this about the state of the Don Woods solver.  It's
really the Woods-Callan-Ettlinger solver now, although the Woods part is
still very much primary -- it still uses Don's basic algorithm.  But my
co-author, Wilson Callan and I did so much surgery on it that I can't really
say for sure whether the flaws that we now have are our fault or inherent in
Don's original approach.  Can't really be tested on Don's original code
because a good part of what we did was to speed it up, and Don's original
just runs too slow on many hands.

    I haven't yet looked at the sites you gave me, but I'd like to ask you
some questions.  Do you provide the means to ask it to solve a range of
hands?  Do you allow for a non-standard number of freecells?

    Where are you located, geography-wise?  I'm in the New York City area.
Hmmm, that E-mail address, ending in "ac.il".  Could that mean Illinois?  Or
is there some country I can't think of beginning with "il"?   Illyrium?

Best regards,  ---------------Adrian


