Return-Path: <aettlinger@worldnet.att.net>
Delivered-To: shlomif@vipe.technion.ac.il
Received: (qmail 1618 invoked from network); 16 Nov 2001 23:55:27 -0000
Received: from mtiwmhc24.worldnet.att.net (204.127.131.49)
  by vipe.technion.ac.il with SMTP; 16 Nov 2001 23:55:27 -0000
Received: from computer ([12.78.219.69]) by mtiwmhc24.worldnet.att.net
          (InterMail vM.4.01.03.27 201-229-121-127-20010626) with SMTP
          id <20011116235518.SPDU19017.mtiwmhc24.worldnet.att.net@computer>
          for <shlomif@vipe.technion.ac.il>;
          Fri, 16 Nov 2001 23:55:18 +0000
Message-ID: <000b01c16efa$1802ca80$45db4e0c@computer>
From: "Adrian Ettlinger" <aettlinger@worldnet.att.net>
To: "Shlomi Fish" <shlomif@vipe.technion.ac.il>
References: <Pine.LNX.4.33L2.0111161702260.28986-100000@vipe.technion.ac.il>
Subject: Re: Freecell solvers, +
Date: Fri, 16 Nov 2001 18:53:56 -0500
MIME-Version: 1.0
Content-Type: text/plain;
  charset="iso-8859-1"
Content-Transfer-Encoding: 7bit
X-Priority: 3
X-MSMail-Priority: Normal
X-Mailer: Microsoft Outlook Express 5.00.2615.200
X-MimeOLE: Produced By Microsoft MimeOLE V5.00.2615.200
Status: RO
X-Status: A
X-Keywords: 
X-UID: 30
X-KMail-EncryptionState: 
X-KMail-SignatureState: 
X-KMail-MDN-Sent: 

Hi Shlomi,

<<I believe a person can become better without relying on such crutches as
religion.>>
    In theory, yes, and if one wants to be optimistic about human nature.  I
guess I'm just that much of cynic.  But.... I think how one would view this
from the perspective of an Israeli would differ from how an American would
view the question.  There are plenty of arguments from different segments of
American society that would support your view.  The Mafioso are all
Catholic -- but we hardly ever hear of much anti-social behavior from
members of the American Humanist Association.

<<<<Ashkenazy vs. Sephardic?>>
My father's parents came from Poland and my mother was born in Iraq.>>
    I guess that is the distinction then, is it not?  Or was it impolitic of
me to use that A-word and S-word?  Does your mother's family go way back in
Iraq as far as she knows her ancestry?  I. e., back to the Ottoman Empire?

<<Actually, this was just an anecdote because we were discussing 16-bit and
32-bit code.>>
    Understood.

<<The for loop of 100,000 is commented out. Instead it deals all boards
whose indices start at start_board and end at end_board, where stard_board
and end_board are inputted from the command line.
It deals the same board as Freecell Pro (at least up to INT_MAX).>>
    OK, good, I didn't notice the commenting out.  Have you run it much over
a long range of boards?  I'm curious as to how fast it works, i. e., how
many boards per second on the average it provides a result.

<<Microsoft Visual C++ 4.0 comes with the Microsoft Standard C Run-Time
Library..................>>
    That was all very educational for me.  I was not aware of the lineage of
all those various commands I'd been using.

<<No problem. Just give me the declaration of this function, and explain
what you pass to each parameter and what the function should pass in return,
and I'll code it for you.
Please also give complete declaration of all the structs the function
declaration makes use of.>>
    That will be excellent.  And it gives me some homework to do.  Might be
able to get to the first phase within a few days.
I'll let you know.

Best regards,  -------------------------------------Adrian


