Return-Path: <aettlinger@worldnet.att.net>
Delivered-To: shlomif@vipe.technion.ac.il
Received: (qmail 18495 invoked from network); 14 Nov 2001 05:24:35 -0000
Received: from mtiwmhc25.worldnet.att.net (204.127.131.50)
  by vipe.technion.ac.il with SMTP; 14 Nov 2001 05:24:35 -0000
Received: from computer ([12.78.218.83]) by mtiwmhc25.worldnet.att.net
          (InterMail vM.4.01.03.27 201-229-121-127-20010626) with SMTP
          id <20011114052423.FXDP11294.mtiwmhc25.worldnet.att.net@computer>;
          Wed, 14 Nov 2001 05:24:23 +0000
Message-ID: <007f01c16ccc$92435920$53da4e0c@computer>
From: "Adrian Ettlinger" <aettlinger@worldnet.att.net>
To: "Shlomi Fish" <shlomif@vipe.technion.ac.il>
Cc: <fomalhaut@earthlink.net>
References: <Pine.LNX.4.33L2.0111131058530.32074-100000@vipe.technion.ac.il>
Subject: Re: Integrating FCS with Freecell Pro
Date: Tue, 13 Nov 2001 23:49:55 -0500
MIME-Version: 1.0
Content-Type: text/plain;
  charset="iso-8859-1"
Content-Transfer-Encoding: 7bit
X-Priority: 3
X-MSMail-Priority: Normal
X-Mailer: Microsoft Outlook Express 5.00.2615.200
X-MimeOLE: Produced By Microsoft MimeOLE V5.00.2615.200
Status: RO
X-Status: A
X-Keywords: 
X-UID: 21
X-KMail-EncryptionState: 
X-KMail-SignatureState: 
X-KMail-MDN-Sent: 

Hello Shlomi,

    You'll need to bring me up to speed on this.  This is the first I've
heard of Freecell Solver.  I should explain that I do not on an ongoing
basis keep in touch with what's being talked about in the Freecell
community.

    I'm very interested in acquiring an alternative solver to add to FcPro.
As you may know, our version of the Don Woods solver is not flawless and can
give false impossibles, and also "intractables" (bogs down and takes forever
to give a result).  Not that I don't think it's "pretty good", but an
alternative solver would be most interesting to investigate.

    Unfortunately, I'm up to my neck in other stuff right now, but I could
give some time into looking into this, if you'll give me some further
fill-in as to what it's all about.

Best regards,  ----------------Adrian Ettlinger




